version: "3.8"
services:
  mongodb1:
    image: "bitnami/mongodb"
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongodb1
      - MONGODB_REPLICA_SET_KEY=123456789
      - MONGODB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - "mongodb_master_data:/bitnami"

  mongodb2:
    image: "bitnami/mongodb"
    depends_on:
      - mongodb1
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_KEY=123456789
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb1
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=root
    ports:
      - 27018:27017

  mongodb3:
    image: "bitnami/mongodb"
    depends_on:
      - mongodb1
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb1
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=root
      - MONGODB_REPLICA_SET_KEY=123456789
    ports:
      - 27019:27017

  my-fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "my-elastic"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  my-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: $ELASTICSEARCH_PASSWORD

  kibana:
    image: kibana:7.8.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

  my-cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

volumes:
  mongodb_master_data:
    driver: local
  elastic_data:
  cache:
    driver: local
